# Generated by Django 3.0 on 2022-02-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
